<?= $this->doctype() ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?= $this->headTitle('SecuritX Secure Document Uploader')->setSeparator(' - ')->setAutoEscape(false) ?>
		<?= $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?= $this->headLink([
			'rel' => 'shortcut icon',
			'type' => 'image/vnd.microsoft.icon',
			'href' => $this->basePath() . '/img/favicon.ico'
		])
		->prependStylesheet($this->basePath('css/style.css'))
		->prependStylesheet($this->basePath('css/bootstrap.css'))
		//->prependStylesheet($this->basePath('css/bootstrap.min.css'))
		?>

		<!-- Scripts -->
		<?= $this->headScript() ?>
	</head>
	<body>
		<nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button
						class="navbar-toggler"
						type="button"
						data-toggle="collapse"
						data-target="#navbarSupportedContent"
						aria-controls="navbarSupportedContent"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<a class="navbar-brand" href="<?= $this->url('home') ?>">
						<img src="<?= $this->basePath('img/securitx.png') ?>" alt="SecuritX">
					</a>
				</div>
			</div>
		</nav>
		<div class="container">
			<?= $this->content ?>
			<hr>
			<footer>
				<p style="text-align: right">
					SecuritX is free and open-source software. Donate to FOSS developers.
				</p>
			</footer>
		</div>
	</body>
</html>
