<?php
	$this->headTitle('SecuritX: Upload');
?>
<div class="jumbotron">
	<h1 class="display-4">Uploader</h1>
	<p>Hello, <?= $first ?>.<br />
	Use the form below to upload files to <?= $company ?>.<br />
	Combined filesize of selected documents may not exceed <b>500 MB</b>.<br />
	A maximum of 20 files may be selected for upload.

	<hr class="my-4">
<?php
	$submit = $form->get('submit');
	$submit->setAttribute('class', 'btn btn-primary');

	$form->prepare();
	$fileElement = $form->get($short);
	echo $this->form()->openTag($form);
?>
	<div class="form-group">
		<?= $this->formLabel($fileElement) ?>
		<div class="form-element">
			<?= $this->formFile($fileElement) ?>
			<?= $this->formElementErrors($fileElement) ?>
		</div>
	</div>
	<?= $this->formSubmit($form->get('submit')) ?>
	<div id="progress" class="help-block">
		<p>&nbsp;</p>
	</div>
<?= $this->form()->closeTag() ?>
</div>
<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/jquery.form.min.js"></script>
<script>
$(function() {
	$('#<?= $short ?>').on('submit', function(e) {
		e.preventDefault();

		if ($('#pdf-files').val() == '') {
			$('#progress > p').html("Select some files first");
			return;
		}

		$(this).ajaxSubmit({
			beforeSubmit: function(arr, $form, options) {
				$('#progress > p').html('Uploading...');
				$('#submitbutton').prop('disabled', true);
				$('#pdf-files').prop('disabled', true);
				arr.push({ name: "isAjax", value: "1" });
			},
			success: function (response, statusText, xhr, $form) {
				$('#progress > p').html("Finished Processing");
				$('#submitbutton').prop('disabled', false);
				$('#pdf-files').prop('disabled', false);
				var fileInput = $('#pdf-files');
				fileInput.replaceWith( fileInput.val('').clone(true));
			},
			error: function(a, b, c) {
				console.log(a, b, c);
			},
		});
	});
});
</script>
