<?php
	$this->headTitle('SecuritX: Home');
?>
<div class="jumbotron">
	<h1 class="display-4">Welcome to SecuritX</h1>

	<p>SecuritX home of <?= $member->first ?> <?= $member->last ?></p>

	<hr class="my-4">
<?php	if ($member->is_admin) { ?>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/companies/<?= $member->u_key ?>">Edit companies &raquo;</a></p>
<?php	} ?>
<?php if ($member->is_admin || $member->is_editor) { ?>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/invite/<?= $member->u_key ?>">Invite a member &raquo;</a></p>
<?php	}
	if ($member->is_admin || $member->is_editor) { ?>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/send/<?= $member->u_key ?>">Send files to a member &raquo;</a></p>
<?php
		if ($c_downloads) { ?>
	<p><a class="btn btn-secondary btn-lg" href="/securitx/cdownload/<?= $member->u_key ?>">Download available company files &raquo;</a></p>
<?php		}
	}
	if ($has_downloads) { ?>
	<p><a class="btn btn-secondary btn-lg" href="/securitx/download/<?= $member->u_key ?>">Download available personal files &raquo;</a></p>
<?php	}
	if ($member->inviter) { ?>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/send/<?= $member->u_key ?>">Send files to <?= $inviter ?> &raquo;</a></p>
<?php	}
	if ($has_domain && !$member->r_admin && !$member->r_editor && !$member->is_admin && !$member->is_editor) {
		echo "You are an employee of the company. Please request an action below.";
	}
	if ($has_domain && !$member->is_admin && !$member->is_editor) {
		echo "Please wait for an administrator to review your request";
	}
	if (!$member->is_admin && !$member->is_editor && !$has_domain) { ?>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/upload/<?= $member->u_key ?>">Upload files to <?= $company ?> &raquo;</a></p>
<?php	} ?>

<!--/*
		<p><a class="btn btn-secondary btn-lg" href="/securitx/user/<?= $member->u_key ?>">Edit my profile &raquo;</a></p>
*/-->

	<hr class="my-4">
<p>
<?php
	if ($has_domain && !$member->is_admin) {
		if ($member->r_admin && !$member->is_admin) {
			echo "<span class='a a-pad'>Administrator rights have been requested</span>";
		} else if (!$member->r_admin && !$member->is_admin) {
?>

	<a class="a a-pad" href="/securitx/requestadmin/<?= $member->u_key ?>">Request administration rights</a>
<?php
			if (!$member->r_editor && !$member->r_admin) {
?>
	 | <a class="a a-pad" href="/securitx/requesteditor/<?= $member->u_key ?>">Request editor rights</a>

<?php
			} else if ($member->r_editor && !$member->is_editor && !$member->is_admin) {
				echo "|<span class='a a-pad'>Editor rights have been requested</span>";
			}
		}
	}
?>
</p>
</div>
