<?php
	$this->headTitle('SecuritX: Home');
?>
<div class="jumbotron">
	<h1 class="display-4">Welcome to SecuritX</h1>

	<p>SecuritX home of <?= $member->first ?> <?= $member->last ?></p>

	<hr class="my-4">
<?php	if ($member->is_admin) { ?>
		<p><a class="btn btn-secondary btn-lg" style="width: 250px" href="/securitx/companies/<?= $member->u_key ?>">Edit companies &raquo;</a></p>
<?php } ?>
<?php if ($member->is_admin || $member->is_editor) { ?>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/invite/<?= $member->u_key ?>">Invite user &raquo;</a></p>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/send/<?= $member->u_key ?>">Send files &raquo;</a></p>
<?php	}
	if (!$member->is_admin && !$member->is_editor) { ?>
		<p><a class="btn btn-secondary btn-lg" href="/securitx/upload/<?= $member->u_key ?>">Upload files &raquo;</a></p>
<?php	} ?>


		<p><a class="btn btn-secondary btn-lg" style="width: 250px" href="/securitx/user/<?= $member->u_key ?>">Edit my profile &raquo;</a></p>
only display this if there are files to download
	<p><a class="btn btn-secondary btn-lg" href="/securitx/download/<?= $member->u_key ?>">Download files &raquo;</a></p>


check if user has domain name of company and offer request for editor and admin
	<hr class="my-4">
</div>
