<?php
	$this->headTitle('SecuritX: Company Editor');
?>
<div class="jumbotron">
	<h1 class="display-4">Welcome to SecuritX</h1>
<?php	if ($completed) { ?>
	<p>Hello, <?= $member->first ?>.<br />The company has been <?= $action ?>.</p>

	<hr class="my-4">


<?php
		goto done;
	}
?>
	<p>Hello, <?= $member->first ?>.<br />Here, you can <?= $action ?> a company.<br />The primary company can not be deleted.</p>

	<hr class="my-4">

<?php
	if ($action == "delete") {
		$cnt = 0;
		$co_opts = array();
		foreach ($companies as $company) {
			/* we will never remove the primary company */
			if ($cnt == 1) {
				$co_opt = [
					'value' => $company->company_id,
					'label' => $this->escapeHtml($company->name),
				];
				array_push($co_opts, $co_opt);
			}
			$cnt = 1;
		}
		$company_id = $form->get('company_id');
		$company_id->setAttribute('class', 'form-control');
		$company_id->setAttribute('placeholder', 'Select Company');
		$company_id->setValueOptions($co_opts);

		$submit = $form->get('submit');
		$submit->setAttribute('class', 'btn btn-primary');

		$form->setAttribute('action', $this->url('securitx', [
			'action' => 'companies',
			'id' => $member->u_key,
		],
		[
			'query' => [
				$action => '',
			]
		]));
		echo $this->form()->openTag($form);
?>
	<div class="form-group">
	<?= $this->formLabel($company_id) ?>
	<?= $this->formElement($company_id) ?>
	<?= $this->formElementErrors()->render($company_id,
	    ['class' => 'help-block']) ?>
	</div>
	<div class="form-group">
	<span style="color: red; font-weight: bold">
	WARNING!!! Deleting a company is not reversible!<br />
	WARNING!!! This action will delete the company and all of its files!<br />
	WARNING!!! This action will delete all company members and their files!<br />
	WARNING!!! Make a backup of your database and files before proceeding if you want to recover!<br />
	WARNING!!! Pressing the 'Delete Company' button will not ask for a confirmation!</span><br/>
	</div>
<?php
		echo $this->formSubmit($form->get('submit'));
		echo $this->form()->closeTag();
		goto done;
	}
	$name = $form->get('name');
	$name->setAttribute('class', 'form-control');
	$name->setAttribute('placeholder', 'Company Name');

	$short = $form->get('short');
	$short->setAttribute('class', 'form-control');
	$short->setAttribute('placeholder', 'Short Name');

	$domain = $form->get('domain');
	$domain->setAttribute('class', 'form-control');
	$domain->setAttribute('placeholder', 'Email Domain');

	$phone = $form->get('phone');
	$phone->setAttribute('class', 'form-control');
	$phone->setAttribute('placeholder', 'Phone Number');

	$downloads = $form->get('downloads');
	$downloads->setAttribute('class', 'form-control');
	$downloads->setAttribute('placeholder',
	    'Enable Browser Downloads');

	$submit = $form->get('submit');
	$submit->setAttribute('class', 'btn btn-primary');


	$form->setAttribute('action', $this->url('securitx', [
		'action' => 'companies',
		'id' => $member->u_key,
	],
	[
		'query' => [
			$action => '',
		]
	]));
	$form->prepare();

	echo $this->form()->openTag($form);
?>
	<div class="form-group">
	<?= $this->formLabel($name) ?>
	<?= $this->formElement($name) ?>
	<?= $this->formElementErrors()->render($name,
	    ['class' => 'help-block']) ?>
	</div>

	<div class="form-group">
	<?= $this->formLabel($short) ?>
	<?= $this->formElement($short) ?>
	<?= $this->formElementErrors()->render($short,
	    ['class' => 'help-block']) ?>
	<p style="color: red"><?= $exists ?></p>
	</div>

	<div class="form-group">
	<?= $this->formLabel($phone) ?>
	<?= $this->formElement($phone) ?>
	<?= $this->formElementErrors()->render($phone,
	    ['class' => 'help-block']) ?>
	<p style="color: red"><?= $valid_phone ?></p>
	</div>

	<div class="form-group">
	<?= $this->formLabel($domain) ?>
	<?= $this->formElement($domain) ?>
	<?= $this->formElementErrors()->render($domain,
	    ['class' => 'help-block']) ?>
	<p style="color: red"><?= $valid_domain ?></p>
	</div>

	<div class="form-group">
	<?= $this->formLabel($downloads) ?> (if you plan to enable automatic file handling via other scripting, do not enable this)
	<div class="form-group-left">
	<?= $this->formElement($downloads) ?>
	<?= $this->formElementErrors()->render($downloads,
	    ['class' => 'help-block']) ?>
	</div>
	</div>

<?php
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
done:
?>
	<br /><p><a class="a a-pad" href="/securitx/home/<?= $member->u_key ?>">Go home</a></p>
</div>
